behaviors:
  SoccerTwos:
    trainer_type: poca
    hyperparameters:
      batch_size: 2048
      buffer_size: 1000000 # 2048000
      learning_rate: 0.0001
      beta:  0.01 # 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5 # 3
      learning_rate_schedule: linear # constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3 # 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 1000000
    max_steps: 300000000
    threaded: false
    time_horizon: 1000 # 2000
    summary_freq: 10000
    self_play:
      save_steps: 50000
      team_change: 200000
      swap_steps: 10000 # 2000
      window: 20 # 15 #10
      play_against_latest_model_ratio: 0.2 #  0.5 # 0.3 # 0.5
      initial_elo: 1200.0
